### PR TITLE
navigation bar, sleep buddy on home page, updated tos

### PR DESCRIPTION
**Pull request by jut008**

### CODE REVIEW

**Review by Shuzhengz — DISMISSED** [review]
we could put an icon like somewhere here:

image

but lgtm

**Review by Shuzhengz — DISMISSED** [review]
lgtm

**Comment by jut008** [comment]
i'm waiting on journal page to be added, and ill add it to our nav bar

**Comment by jut008** [comment]
done

**Review by Shuzhengz — CHANGES_REQUESTED** [review]
the icon in the tabs bar is back to the default react logo again

**Comment by Shuzhengz** [comment]
> the icon in the tabs bar is back to the default react logo again

wait nvm it just fixed itself

**Review by Shuzhengz — APPROVED** [review]
lgtm

**Pull request merged**
