### PR TITLE
Music Button

### LINKED ISSUE #25: Music Button
add the music button on home page

### PR DESCRIPTION
**Pull request by Shuzhengz**
Adds the music button on the main page, closes #25

### CODE REVIEW

**Review by aishahmed — DISMISSED** [review]
looks good

**Review by JingtingL — COMMENTED** [review]
looks good

**Comment by Shuzhengz** [comment]
ok should be done now

**Review by aishahmed — APPROVED** [review]
looks good

**Review by JingtingL — COMMENTED** [review]
Looks good

**Review by JingtingL — APPROVED** [review]
Looks good

**Pull request merged**
